name: first-workflow
on: [push]
jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hllo
        run: echo "Hello World"
      - name: multiple line cmd
        run: |
          node -v
          npm -v